name: Fetch Postgres Dynamic Secrets
'on': push
jobs:
  fetch_postgres_dynamic_secrets:
    runs-on: self-hosted
    name: Fetch Postgres Dynamic Secrets
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Fetch dynamic secrets from Akeyless
        id: fetch-dynamic-secrets
        uses: akeyless-community/akeyless-github-action@v1.0.1
        with:
          access-id: '${{ secrets.ACCESS_ID }}'
          dynamic-secrets: |
            - name: "/PTSA/PTSA_DynamicDB"
              output-name: "postgres_dynamic_secret"
          access-type: jwt
          export-secrets-to-outputs: true
          export-secrets-to-environment: true
          api-url: 'https://cmmel.mymfademo.com/akeyless-api/v2/'
      - name: Export Secrets to Environment
        run: |
           echo '${{ steps.fetch-dynamic-secrets.outputs.postgres_dynamic_secret }}' | jq -r 'to_entries|map("JWT_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
      - name: Verify Vars
        run: |
          echo "access_key_id: ${{ env.JWT_access_key_id }}"
          echo "id: ${{ env.JWT_id }}"
          echo "secret_access_key: ${{ env.JWT_secret_access_key }}"
          echo "type: ${{ env.JWT_type }}"         
